### PR TITLE
Use new API make it compile in Qt6

### PR DESCRIPTION
**Pull request by ho-229**

### CODE REVIEW

**Comment by Inokinoki** [comment]
LGTM, let me trigger the CI

**Comment by ho229v3666** [comment]
Why is the linux ci qt version is 5.12😂

**Comment by Inokinoki** [comment]
> Why is the linux ci qt version is 5.12😂

You can add one for Qt6

**Comment by Inokinoki** [comment]
> > Why is the linux ci qt version is 5.12😂
> 
> Need to add one for Qt6, otherwise, the behavior cannot be checked in CI...

Let us try to add a CI for Qt6

**Comment by ho229v3666** [comment]
👀

**Comment by Inokinoki** [comment]
The build is successful. It seems that `windeployqt` has some breaking changes, which will be fixed in another commit.

**Pull request merged**
