### PR TITLE
refactor: use range-based for loop to enhance readability

### PR DESCRIPTION
**Pull request by Integral-Tech**

### CODE REVIEW

**Comment by Inokinoki** [comment]
Wait for test on FreeBSD to check G++ version and standard flag to add @Inokinoki

**Comment by Inokinoki** [comment]
> Wait for test on FreeBSD to check G++ version and standard flag to add @Inokinoki

Thanks! It works with g++ on FreeBSD after **specifying the CXX standard version**:

Screenshot 2024-11-07 at 7 33 50 PM

Please explicitly update `CMAKE_CXX_STANDARD` to 17:

Screenshot 2024-11-07 at 7 31 44 PM

**Comment by Integral-Tech** [comment]
@Inokinoki Done :)

**Comment by Inokinoki** [comment]
It requires glibc 2.34 thererfore:

```
$ ldd /mnt/c/QEFI\ Entry\ Manager\ x86_64\ AppImage/QEFIEntryManager
/mnt/c/QEFI Entry Manager x86_64 AppImage/QEFIEntryManager: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /mnt/c/QEFI Entry Manager x86_64 AppImage/QEFIEntryManager)
```

Let me check the compatibilities in any case

**Comment by Integral-Tech** [comment]
@Inokinoki Fixed :)

**Review by Inokinoki — APPROVED** [review]
Great! 🙏 Thanks very much!

**Pull request merged**
